package tips

// Facts are coding-related trivia shown in the idle info line after every
// command tip has rotated through once. One line each, no trailing period,
// same voice as the tips.
var Facts = []string{
	"git was originally written in about 10 days by Linus Torvalds in 2005 to replace BitKeeper",
	"a git commit hash is a SHA-1 checksum of the entire snapshot of your repo at that moment",
	"`git blame` only reports the last commit to touch a line — the origin of the code is often much older",
	"a git branch is just a 41-byte file containing a commit hash, which is why branching is nearly free",
	"`git reflog` records every position HEAD has ever taken — most 'lost' commits are recoverable through it",
	"git's index (staging area) exists so a commit can contain a mix of file states, not just the working tree",
	"the first commit in a git repo has no parent — `git rev-list --max-parents=0 HEAD` finds it",
	"`git bisect` binary-searches your history for the commit that introduced a bug, usually in O(log n) steps",
	"a git merge commit has two parents; a regular commit has one; the root commit has none",
	"git stores full snapshots, not diffs — the 'diff' you see is computed on demand",
	"Go compiles to a single static binary by default — no runtime dependency to ship",
	"Go's goroutines start with a 2 KB stack that grows and shrinks on demand, so thousands can idle cheaply",
	"gofmt has no configuration options on purpose — the entire ecosystem shares one style",
	"Go methods with a pointer receiver mutate the value; value receivers get a copy, always",
	"a Go interface is satisfied implicitly — the implementing package never needs to import the interface",
	"`defer` args are evaluated at the defer site, not when the deferred call runs — classic closure gotcha",
	"Go's `nil` interface is only nil when both its type and value are nil — a typed nil pointer in an interface is not nil",
	"strings.Builder beats `+` concatenation in loops because Go strings are immutable",
	"Go channels close on the sender's side only — closing on the receiver's side is a bug",
	"the Go compiler can inline small functions, which is why simple getters are effectively free",
	"`go test -race` instruments memory accesses at compile time to catch data races deterministically enough to trust",
	"Go's GC is concurrent and sub-millisecond pause-oriented — most pauses are measured in tens of microseconds",
	"a Unix exit code is 8 bits — 256 wraps to 0, which is why exit codes cap meaningfully at 255",
	"stderr is unbuffered on most terminals while stdout is line-buffered — interleaving them can reorder output",
	"the terminal bell (ASCII 7, '\\a') dates to literal physical bells on teletypes",
	"Ctrl+C sends SIGINT, Ctrl+Z sends SIGTSTP — both are catchable, unlike SIGKILL",
	"the `less` pager reads from stdin, so `git diff | less` works with any command's output",
	"escape codes like '\\x1b[2J' are why terminal programs can clear screens — they're just bytes on stdout",
	"the QWERTY layout predates computers entirely — it was designed for 1870s typewriters",
	"UTF-8 was co-designed by Ken Thompson and Rob Pike in 1992 over a placemat in a New Jersey diner",
	"UTF-8 is self-synchronizing — you can join a byte stream mid-character and resync within a few bytes",
	"ASCII was designed with bit 6 as a case toggle — 'A' differs from 'a' by exactly 32",
	"a regex `.*` is greedy but `.*?` is lazy — the difference decides which quote a pattern matches first",
	"regular expressions can't count nested parentheses — that needs a parser, not a regex",
	"backtracking regex engines can take exponential time — catastrophic backtracking on 'a*a*a*...b'",
	"RE2 (used by Go's regexp) never backtracks, trading some expressiveness for linear-time guarantees",
	"HTTP 418 'I'm a teapot' is a 1998 April Fools joke that ended up in real status-code libraries",
	"HTTP/2 multiplexes many requests over one TCP connection, eliminating head-of-line blocking at the HTTP layer",
	"a TCP connection is identified by the 4-tuple of source IP, source port, destination IP, destination port",
	"port 0 is reserved — requesting it makes the OS assign an ephemeral port",
	"DNS resolution typically uses UDP port 53 but falls back to TCP for responses over 512 bytes",
	"curl's default timeout is infinite; most languages' HTTP clients default to something else — always set one",
	"SQL injection happens because string concatenation builds code, not data — parameterized queries fix it",
	"SQLite is likely the most deployed database in the world — it ships inside nearly every phone and browser",
	"Postgres MVCC keeps old row versions around until VACUUM reclaims them — bloat is a real cost",
	"a database index is a separate data structure, not a reordering of the table — it costs write throughput",
	"the CAP theorem says a distributed store can only guarantee two of consistency, availability, and partition tolerance",
	"idempotency keys let retries be safe — an API call retried with the same key won't double-charge",
	"the two-second rule of thumb: a UI interaction under 100ms feels instant, over 1s needs a progress indicator",
	"Fitts's law: big targets close to the cursor are faster to hit — the reason window edges make great resize handles",
	"muscle memory beats menus: keyboard shortcuts are faster because they avoid the visual search loop",
	"the Dvorak and Colemak layouts exist because QWERTY's inefficiency was never revisited for computers",
	"floating-point can't represent 0.1 exactly — 0.1 + 0.2 != 0.3 in every IEEE 754 language",
	"NULL in SQL is not a value — it's the absence of one, and NULL = NULL returns NULL, not true",
	"the billion-dollar mistake is Tony Hoare's name for the null reference he invented in 1965",
	"fibonacci hashing appears in real hash tables because multiplying by phi distributes keys well",
	"hash maps degrade to O(n) when all keys collide — which is how hash-flooding DoS attacks work",
	"cron's smallest unit is one minute — sub-minute scheduling needs a wrapper loop or a job queue",
	"a Unix socket is a file whose contents live in kernel memory, not on disk",
	"vim's modal editing came from the adm-3a terminal, whose ESC key sat where Tab is now",
	"the 80-column terminal width descends from IBM punch cards, which had 80 columns",
	"the 'save' icon is a floppy disk most users have never touched — skeuomorphism outliving its referent",
	"Moore's law is about transistor density, not speed — clock speeds plateaued around 2004",
	"branch prediction is why sorting data can make a loop faster — predictable branches don't flush the pipeline",
	"cache lines are 64 bytes on most CPUs — an array-of-structs walk touches a fraction of the memory a struct-of-arrays walk does",
	"premature optimization is only half the saying — Knuth's full point was about measuring before optimizing",
	"a 4096-bit RSA key is not 'twice as secure' as 2048-bit — security scales with key length in bits, not multiples",
	"hashing is one-way, encryption is two-way — 'encrypting a password' is almost always the wrong word",
	"bcrypt and argon2 are slow on purpose — password hashing wants to be expensive, unlike normal hashing",
	"the modern consensus on passwords is length over complexity — a five-word passphrase beats P@ssw0rd!",
}
