package tips

// summary tip material (from the command registry).
func init() {
	register(CommandTip{
		Name:         "summary",
		Tip:          "model-written summary of the session so far",
		Personalized: "",
		Body:         "# /summary\n\nAsks the model to write a concise summary of the conversation so far — the\narc of what was asked, decided and changed — and shows it in the transcript.\n\n## When to use\n- Handing off to a colleague or a future session.\n- Before `/compact` or `/new` when you want the essence kept in view.\n\n## Notes\n- The summary is generated by the active model; it costs one completion.\n- It is added to the conversation, not persisted as a file (use `/export`\n  for a file).\n\n## Related\n- `/recap` — the deterministic digest (no model call, instant).\n- `/export` — the full raw transcript as Markdown.",
	})
}
