package prompt

import (
	"context"
	"strings"

	"github.com/iSundram/Automergent/internal/shared"
)

// PhaseClassifier classifies the first user message into phases and tasks.
type PhaseClassifier struct {
	phaseManager *PhaseManager
	llmClient    LLMClient
}

// NewPhaseClassifier creates a new phase classifier.
func NewPhaseClassifier(phaseManager *PhaseManager, llmClient LLMClient) *PhaseClassifier {
	return &PhaseClassifier{
		phaseManager: phaseManager,
		llmClient:    llmClient,
	}
}

// ClassificationResult contains the result of first-message classification.
type ClassificationResult struct {
	PrimaryPhase           shared.AgentPhase
	SecondaryPhases        []shared.AgentPhase
	Tasks                  []shared.TaskSpec
	RequiresClarification  bool
	ClarificationQuestions []string
	Violations             []shared.ViolationCheck
	IsDirectQuestion       bool
	DirectAnswer           string
}

// Classify classifies the first user message.
func (c *PhaseClassifier) Classify(ctx context.Context, firstMessage string, availableFiles []string) (*ClassificationResult, error) {
	result := &ClassificationResult{
		PrimaryPhase:    shared.PhaseInit,
		SecondaryPhases: []shared.AgentPhase{},
		Tasks:           []shared.TaskSpec{},
	}
	
	// 1. Check for violations
	if violation := c.checkViolation(firstMessage); violation != nil {
		result.Violations = append(result.Violations, *violation)
	}
	
	// 2. Check if it's a direct question (answer in init phase)
	if c.isDirectQuestion(firstMessage) {
		result.IsDirectQuestion = true
		result.PrimaryPhase = shared.PhaseInit
		// Direct answer will be generated by the model
		return result, nil
	}
	
	// 3. Check for clarification needs
	questions := c.checkClarification(firstMessage)
	if len(questions) > 0 {
		result.RequiresClarification = true
		result.ClarificationQuestions = questions
		result.PrimaryPhase = shared.PhaseInit
		return result, nil
	}
	
	// 4. Classify intent using LLM for complex cases
	intentResult, err := c.classifyWithLLM(ctx, firstMessage, availableFiles)
	if err == nil && intentResult != nil {
		result.PrimaryPhase = intentResult.PrimaryPhase
		result.SecondaryPhases = intentResult.SecondaryPhases
		result.Tasks = intentResult.Tasks
		return result, nil
	}
	
	// 5. Fallback to keyword-based classification
	phase, tasks, questions, violation := c.phaseManager.ClassifyAndRoute(firstMessage)
	result.PrimaryPhase = phase
	result.Tasks = tasks
	result.ClarificationQuestions = questions
	if violation != nil {
		result.Violations = append(result.Violations, *violation)
	}
	
	return result, nil
}

// isDirectQuestion checks if the message is a simple direct question (not a coding task).
func (c *PhaseClassifier) isDirectQuestion(message string) bool {
	lower := strings.ToLower(strings.TrimSpace(message))
	
	// First, check for coding task keywords - if present, it's NOT a direct question
	codeKeywords := []string{
		"implement", "create", "build", "fix", "refactor", "debug", 
		"write", "code", "function", "class", "api", "feature",
		"bug", "error", "issue", "refactor", "optimize", "add",
		"modify", "change", "update", "delete", "remove", "test",
		"deploy", "build", "compile", "run", "execute",
	}
	for _, kw := range codeKeywords {
		if strings.Contains(lower, kw) {
			return false // This is a coding task, not a direct question
		}
	}
	
	directPatterns := []string{
		"what does", "what is", "what are", "what happens",
		"how does", "how to", "how can", "how do",
		"who are you", "who am i", "what can you do",
		"hello", "hi", "hey", "hiya",
		"thanks", "thank you", "ok", "okay",
		"yes", "no", "yep", "nope",
	}
	
	for _, pattern := range directPatterns {
		if strings.HasPrefix(lower, pattern) || lower == pattern {
			return true
		}
	}
	
	// Short questions
	if len(strings.Fields(lower)) <= 8 && strings.HasSuffix(lower, "?") {
		return true
	}
	
	return false
}

// checkViolation checks for policy violations.
func (c *PhaseClassifier) checkViolation(message string) *shared.ViolationCheck {
	lower := strings.ToLower(message)
	
	violationPatterns := map[shared.ViolationType][]struct {
		pattern   string
		severity  shared.ViolationSeverity
	}{
		shared.ViolationHacking: {
			{"hack", shared.ViolationSeverityHigh},
			{"exploit", shared.ViolationSeverityCritical},
			{"vulnerability", shared.ViolationSeverityMedium},
			{"penetration", shared.ViolationSeverityHigh},
			{"bypass", shared.ViolationSeverityHigh},
			{"backdoor", shared.ViolationSeverityCritical},
			{"injection", shared.ViolationSeverityCritical},
			{"xss", shared.ViolationSeverityHigh},
			{"csrf", shared.ViolationSeverityHigh},
			{"rce", shared.ViolationSeverityCritical},
		},
		shared.ViolationIllegal: {
			{"illegal", shared.ViolationSeverityHigh},
			{"unauthorized", shared.ViolationSeverityHigh},
			{"pirate", shared.ViolationSeverityMedium},
			{"crack", shared.ViolationSeverityHigh},
			{"keygen", shared.ViolationSeverityHigh},
			{"license bypass", shared.ViolationSeverityHigh},
		},
		shared.ViolationHarmful: {
			{"malware", shared.ViolationSeverityCritical},
			{"virus", shared.ViolationSeverityCritical},
			{"ransomware", shared.ViolationSeverityCritical},
			{"keylogger", shared.ViolationSeverityCritical},
			{"steal", shared.ViolationSeverityHigh},
			{"destroy", shared.ViolationSeverityHigh},
			{"delete all", shared.ViolationSeverityHigh},
			{"wipe", shared.ViolationSeverityHigh},
			{"ddos", shared.ViolationSeverityCritical},
		},
		shared.ViolationCredentials: {
			{"password", shared.ViolationSeverityHigh},
			{"credential", shared.ViolationSeverityHigh},
			{"secret", shared.ViolationSeverityHigh},
			{"api key", shared.ViolationSeverityCritical},
			{"token", shared.ViolationSeverityHigh},
			{"ssh key", shared.ViolationSeverityCritical},
			{"private key", shared.ViolationSeverityCritical},
			{"access key", shared.ViolationSeverityCritical},
		},
		shared.ViolationSecurity: {
			{"disable security", shared.ViolationSeverityHigh},
			{"bypass auth", shared.ViolationSeverityHigh},
			{"no auth", shared.ViolationSeverityMedium},
			{"skip verification", shared.ViolationSeverityMedium},
			{"disable ssl", shared.ViolationSeverityHigh},
			{"insecure", shared.ViolationSeverityMedium},
		},
	}
	
	for vType, patterns := range violationPatterns {
		for _, p := range patterns {
			if strings.Contains(lower, p.pattern) {
				return &shared.ViolationCheck{
					Type:        vType,
					Severity:    p.severity,
					UserMessage: message,
					Count:       1,
					Action:      "warn",
				}
			}
		}
	}
	
	return nil
}

// checkClarification checks for ambiguous requests.
func (c *PhaseClassifier) checkClarification(message string) []string {
	lower := strings.ToLower(message)
	var questions []string
	
	// Multiple intent keywords
	intentKeywords := map[string][]string{
		"explore":   {"find", "search", "look for", "where is", "how does", "explore", "discover"},
		"implement": {"implement", "create", "build", "make", "add", "write", "develop"},
		"fix":       {"fix", "bug", "error", "issue", "broken", "repair", "resolve"},
		"plan":      {"plan", "design", "architecture", "approach", "strategy", "roadmap"},
		"question":  {"what", "how", "why", "explain", "tell me", "describe"},
		"test":      {"test", "verify", "validate", "check", "ensure"},
		"refactor":  {"refactor", "restructure", "reorganize", "clean up", "improve"},
	}
	
	detectedIntents := []string{}
	for intent, keywords := range intentKeywords {
		for _, kw := range keywords {
			if strings.Contains(lower, kw) {
				detectedIntents = append(detectedIntents, intent)
				break
			}
		}
	}
	
	if len(detectedIntents) > 1 {
		questions = append(questions, "Your request could mean multiple things: "+strings.Join(detectedIntents, ", ")+". Which is the primary goal?")
	}
	
	// Vague scope
	vaguePatterns := []string{"make it better", "improve", "optimize", "clean up", "fix it"}
	for _, p := range vaguePatterns {
		if strings.Contains(lower, p) && len(detectedIntents) == 0 {
			questions = append(questions, "Your request is vague. What specifically should I improve/fix/optimize?")
			break
		}
	}
	
	// Unrelated personal content mixed with task
	personalPatterns := []string{"i like", "i love", "i hate", "i'm tired", "i don't sleep", "coffee", "lunch", "dinner"}
	for _, p := range personalPatterns {
		if strings.Contains(lower, p) && len(detectedIntents) > 0 {
			questions = append(questions, "Your message contains personal content unrelated to the task. Should I focus only on the coding task?")
			break
		}
	}
	
	// Conflicting instructions
	if strings.Contains(lower, "don't") && strings.Contains(lower, "do") {
		questions = append(questions, "Your request contains conflicting instructions. Please clarify.")
	}
	
	return questions
}

// classifyWithLLM uses LLM for more sophisticated classification.
func (c *PhaseClassifier) classifyWithLLM(ctx context.Context, message string, availableFiles []string) (*ClassificationResult, error) {
	if c.llmClient == nil {
		return nil, nil
	}
	
	systemPrompt := `Classify the user's first message into phases and tasks.
Return JSON only with this structure:
{
  "primary_phase": "init|explore|plan|build|verify",
  "secondary_phases": ["explore", "plan"],
  "tasks": [
    {"type": "explore|plan|build|verify|direct|question", "description": "...", "role": "explore|planner|implementer|tester|assistant", "priority": 1}
  ],
  "requires_clarification": false,
  "clarification_questions": [],
  "is_direct_question": false
}

Phases:
- init: First message, classification, direct Q&A
- explore: Codebase search, reading, understanding (read-only)
- plan: Design, architecture, task breakdown
- build: Implementation, coding, editing
- verify: Testing, linting, validation

Task types: explore, plan, build, verify, direct, question`

	userPrompt := `User message: ` + message + `

Available files (sample): ` + strings.Join(availableFiles[:min(20, len(availableFiles))], ", ") + `

Classify this request.`

	// This would call the LLM - for now return nil to use fallback
	_ = userPrompt
	_ = systemPrompt
	
	return nil, nil // Fallback to keyword-based
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}